### ISSUE TITLE
[Docs] Import paths are missing on Android setup documentation

### ISSUE THREAD

**Issue by lukebars** [optimove-tech/Optimove-SDK-React-Native#5]
Hi,

The setup documentation states that developers need to add Optimove configuration to `MainApplication.java`, yet these statements result in code which is undefined.

https://github.com/optimove-tech/Optimove-SDK-React-Native/wiki/Initializing-the-sdk#android

These imports are missing:
```java
import com.optimove.android.OptimoveConfig;
import com.optimove.reactnative.OptimoveReactNativeConfig;
import com.optimove.reactnative.OptimoveReactNativeInitializer;
```

**Comment by lukebars** [comment]
Plus, this line is incorrect, as it lacks expression:

```java
.enableInAppWithConsentStrategy(OptimoveConfig.InAppConsentStrategy)
```

it should be one of these two:

```java
.enableInAppWithConsentStrategy(OptimoveConfig.InAppConsentStrategy.AUTO_ENROLL)
.enableInAppWithConsentStrategy(OptimoveConfig.InAppConsentStrategy.EXPLICIT_BY_USER)
```

**Comment by k-antipochkin** [comment]
Hey, thanks for the feedback. I have updated the wiki docs to clarify the above.
