### ISSUE TITLE
Handling different environments

### ISSUE THREAD

**Issue by lukebars** [optimove-tech/Optimove-SDK-React-Native#7]
What is the suggested way for switching between Optimove production / sandbox environments when we have to pass the keys on the native side?

**Comment by cgwyllie** [comment]
Hi @lukebars, thanks for reaching out about this!

We would suggest making use of multiple native build targets and defining resources per variant.

There's a 3rd-party react-native package that can help you achieve this (see the "Native Usage" section):

https://github.com/luggit/react-native-config

Hope this helps, but please let us know if you have any further questions around this!

~Chris

**Comment by cgwyllie** [comment]
Hi @lukebars hope the above has answered your question, but please feel free to re-open or reach out to our teams if you have any further questions!
